// export const MOCK_ENVIRONMENTS = ["development", "test"];
// export const {
//   NODE_ENV,
//   REACT_APP_ENVIRONMENT,
//   REACT_APP_FEATURE_BRANCH,
//   REACT_APP_COMMIT_HASH
// } = process.env;
// export const ENVIRONMENT = REACT_APP_ENVIRONMENT || NODE_ENV;
// export const IS_MOCK_ENVIRONMENT = MOCK_ENVIRONMENTS.indexOf(ENVIRONMENT) !== -1;
// export const FEATURE_BRANCH = REACT_APP_FEATURE_BRANCH;
// export const COMMIT_HASH = REACT_APP_COMMIT_HASH;

export const BREAKPOINTS = {
  MOBILE: 767,
  TABLET: 1024,
  LAPTOP: 1279,
  DESKTOP: 1599,
  WIDESCREEN: 1600 // 1600+
};
